<?php

namespace ContainerPraOKQZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCarscrapperCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\CarscrapperCommand' shared autowired service.
     *
     * @return \App\Command\CarscrapperCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'CarscrapperCommand.php';

        $container->privates['App\\Command\\CarscrapperCommand'] = $instance = new \App\Command\CarscrapperCommand(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));

        $instance->setName('carscrapper');
        $instance->setDescription('This is a command for scrapping car data developed by Mouadh El Amri for RV Websolutions Assignment');

        return $instance;
    }
}
