<?php

namespace ContainerPraOKQZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCarscrapperCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\CarscrapperCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'LazyCommand.php';

        return $container->privates['.App\\Command\\CarscrapperCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('carscrapper', [], 'This is a command for scrapping car data developed by Mouadh El Amri for RV Websolutions Assignment', false, #[\Closure(name: 'App\\Command\\CarscrapperCommand')] function () use ($container): \App\Command\CarscrapperCommand {
            return ($container->privates['App\\Command\\CarscrapperCommand'] ?? $container->load('getCarscrapperCommandService'));
        });
    }
}
