<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYs6hqRv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYs6hqRv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYs6hqRv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYs6hqRv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYs6hqRv\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ys6hqRv',
    'container.build_id' => 'db209709',
    'container.build_time' => 1683235449,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYs6hqRv');
